apiVersion: apps/v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DATABASE_USERNAME: postgres
  DATABASE_PASSWORD: superstrongpassword1
  DATABASE_HOST: "34.89.121.66"
  DATABASE_PORT: "5432"
  DATABASE_NAME: postgres
   
  
  kubectl create generic secret mysecret\
  --from-literal=DATABASE_USERNAME=postgres\
  --from-literal=DATABASE_PASSWORD=superstrongpassword1\
  --from-literal=DATABASE_HOST="34.89.121.66"\
  --from-literal=DATABASE_PORT="5432"\
  --from-literal=DATABASE_NAME=postgres\
  --from-literal=MEDIA_SERVICE_URL="http://media-service:80"