apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-deployment
  labels:
    app: charity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: charity
  template:
    metadata:
      labels:
        app: charity
    spec:
      containers:
      - name: charity
        image: eu.gcr.io/cloud-ready-roke-team-4/charity-api:v1.0
        ports:
        - containerPort: 3000
        env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_USERNAME
                optional: false 
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_PASSWORD
                optional: false 
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_HOST
                optional: false 
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_PORT
                optional: false 
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_NAME
                optional: false 
---
  apiVersion: v1
  kind: Service
  metadata:
    name: charity-service
  spec:
    ports:
      - protocol: TCP
        port: 80
        targetPort: 3000
    selector:
      app: charity
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: charity-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /charities
        backend:
          service:
            name: charity-service
            port:
              number: 80